rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-head

notifications:
  irc: "irc.freenode.org#pry"
  recipients:
    - jrmair@gmail.com

branches:
  only:
    - master
    - remove_mri18_support
